# Generated by Django 4.2.5 on 2023-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='oioi',
            field=models.CharField(default='ilana', max_length=200),
            preserve_default=False,
        ),
    ]
