# Generated by Django 4.2.5 on 2023-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_filme_oioi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
