# Generated by Django 4.2.5 on 2023-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_filme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
